/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GiaoDien;

import com.sales.DAO.ColorDAO;
import com.sales.DAO.SizeDAO;
import com.sales.Entity.Color;
import com.sales.Entity.Size;
import com.sales.Utils.XImage;
import com.sales.Utils.XValidate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NganTTK_PC09494
 */
public class FormThuocTinh extends javax.swing.JFrame {
 ColorDAO colorDao = new ColorDAO();
    DefaultTableModel modelColor = new DefaultTableModel();
    DefaultTableModel modelSize = new DefaultTableModel();
    List<Color> listColor = new ArrayList<>();
    List<Size> listSize = new ArrayList<>();
    Color color = new Color();
    SizeDAO sizeDao = new SizeDAO();
    Size size = new Size();
    int index = 0;
    /**
     * Creates new form FormMauSac
     */
    public FormThuocTinh() {
        initComponents();
        init();
    }

    public void init() {
        setLocationRelativeTo(null);
        setIconImage(XImage.XImage());
        setTitle("PHẦN MỀM QUẢN LÝ GIÀY THỂ THAO");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
         setTableTitleColor();
        setTableTitleSize();
        loadTableColor();
        loadTableSize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgrMauSac = new javax.swing.ButtonGroup();
        bgrKichThuoc = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMauSac = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMauSac = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        txtTimKiemMauSac = new javax.swing.JTextField();
        btnTimKiemMauSac = new javax.swing.JButton();
        btnThemMauSac = new javax.swing.JButton();
        btnSuaMauSac = new javax.swing.JButton();
        btnXoaMauSac = new javax.swing.JButton();
        btnThoatMauSac = new javax.swing.JButton();
        btnMoiMauSac = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cknHoatDong = new javax.swing.JCheckBox();
        cknNgungHoatDong = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtSize = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKichThuoc = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        txtTimKiemKichThuoc = new javax.swing.JTextField();
        btnTimKiemKichThuoc = new javax.swing.JButton();
        btnThemKichThuoc = new javax.swing.JButton();
        btnSuaKichThuoc = new javax.swing.JButton();
        btnXoaKichThuoc = new javax.swing.JButton();
        btnThoatKichThuoc = new javax.swing.JButton();
        btnMoiKichThuoc = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cknHoatDongKichThuoc = new javax.swing.JCheckBox();
        cknNgungHoatDongKickThuoc = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Màu sắc");

        txtMauSac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMauSacActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("MÀU SẮC");

        tblMauSac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMauSac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMauSacMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMauSac);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtTimKiemMauSac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemMauSacKeyReleased(evt);
            }
        });

        btnTimKiemMauSac.setText("TÌM KIẾM");
        btnTimKiemMauSac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemMauSacActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(txtTimKiemMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(btnTimKiemMauSac)
                .addGap(65, 65, 65))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiemMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiemMauSac))
                .addGap(33, 33, 33))
        );

        btnThemMauSac.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemMauSac.setText("Thêm");
        btnThemMauSac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMauSacActionPerformed(evt);
            }
        });

        btnSuaMauSac.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSuaMauSac.setText("Sửa");
        btnSuaMauSac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaMauSacActionPerformed(evt);
            }
        });

        btnXoaMauSac.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoaMauSac.setText("Xóa");
        btnXoaMauSac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaMauSacActionPerformed(evt);
            }
        });

        btnThoatMauSac.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThoatMauSac.setText("Thoát");
        btnThoatMauSac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatMauSacActionPerformed(evt);
            }
        });

        btnMoiMauSac.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMoiMauSac.setText("Mới");
        btnMoiMauSac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiMauSacActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Trạng Thái");

        bgrMauSac.add(cknHoatDong);
        cknHoatDong.setText("Hoạt Động");

        bgrMauSac.add(cknNgungHoatDong);
        cknNgungHoatDong.setText("Ngừng Hoạt Động");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(cknHoatDong)
                                .addGap(61, 61, 61)
                                .addComponent(cknNgungHoatDong))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(53, 53, 53))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnThemMauSac)
                .addGap(69, 69, 69)
                .addComponent(btnSuaMauSac)
                .addGap(57, 57, 57)
                .addComponent(btnXoaMauSac)
                .addGap(58, 58, 58)
                .addComponent(btnThoatMauSac)
                .addGap(58, 58, 58)
                .addComponent(btnMoiMauSac)
                .addGap(124, 124, 124))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel7)
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cknHoatDong)
                    .addComponent(cknNgungHoatDong))
                .addGap(113, 113, 113))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemMauSac)
                    .addComponent(btnSuaMauSac)
                    .addComponent(btnXoaMauSac)
                    .addComponent(btnThoatMauSac)
                    .addComponent(btnMoiMauSac))
                .addGap(14, 14, 14))
        );

        jTabbedPane1.addTab("MÀU SÁC", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Kích thước");

        txtSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSizeActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("KÍCH THƯỚC");

        tblKichThuoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKichThuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKichThuocMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblKichThuoc);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtTimKiemKichThuoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKichThuocKeyReleased(evt);
            }
        });

        btnTimKiemKichThuoc.setText("TÌM KIẾM");
        btnTimKiemKichThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemKichThuocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(txtTimKiemKichThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(btnTimKiemKichThuoc)
                .addGap(65, 65, 65))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiemKichThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiemKichThuoc))
                .addGap(33, 33, 33))
        );

        btnThemKichThuoc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemKichThuoc.setText("Thêm");
        btnThemKichThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemKichThuocActionPerformed(evt);
            }
        });

        btnSuaKichThuoc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSuaKichThuoc.setText("Sửa");
        btnSuaKichThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaKichThuocActionPerformed(evt);
            }
        });

        btnXoaKichThuoc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoaKichThuoc.setText("Xóa");
        btnXoaKichThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaKichThuocActionPerformed(evt);
            }
        });

        btnThoatKichThuoc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThoatKichThuoc.setText("Thoát");
        btnThoatKichThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatKichThuocActionPerformed(evt);
            }
        });

        btnMoiKichThuoc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMoiKichThuoc.setText("Mới");
        btnMoiKichThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiKichThuocActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Trạng Thái");

        bgrKichThuoc.add(cknHoatDongKichThuoc);
        cknHoatDongKichThuoc.setText("Hoạt Động");

        bgrKichThuoc.add(cknNgungHoatDongKickThuoc);
        cknNgungHoatDongKickThuoc.setText("Ngừng Hoạt Động");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnThemKichThuoc)
                        .addGap(69, 69, 69)
                        .addComponent(btnSuaKichThuoc)
                        .addGap(57, 57, 57)
                        .addComponent(btnXoaKichThuoc)
                        .addGap(58, 58, 58)
                        .addComponent(btnThoatKichThuoc)
                        .addGap(58, 58, 58)
                        .addComponent(btnMoiKichThuoc))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSize, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(cknHoatDongKichThuoc)
                                        .addGap(61, 61, 61)
                                        .addComponent(cknNgungHoatDongKickThuoc))))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(53, 53, 53))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(txtSize, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel8)
                .addGap(35, 35, 35)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cknHoatDongKichThuoc)
                    .addComponent(cknNgungHoatDongKickThuoc))
                .addGap(110, 110, 110))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemKichThuoc)
                    .addComponent(btnSuaKichThuoc)
                    .addComponent(btnXoaKichThuoc)
                    .addComponent(btnThoatKichThuoc)
                    .addComponent(btnMoiKichThuoc))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1374, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 2, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 3, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 561, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("KÍCH THƯỚC", jPanel4);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("QUẢN LÝ THUỘC TÍNH");

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("THÔNG TIN THUỘC TÍNH");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTabbedPane1)))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    /**
     * Creates new form FormMauSac
     */
  

    public void loadTableColor() {

        modelColor.setRowCount(0);
        listColor = colorDao.selectAll();
        for (Color cl : listColor) {
            Object[] row = {
                cl.getId(),
                cl.getName(),
                cl.getActive() ? "Hoạt Động" : "Ngừng Hoạt động"

            };
            modelColor.addRow(row);
        }
        tblMauSac.setModel(modelColor);
    }

    public void setTableTitleColor() {
        modelColor.addColumn("Mã Số");
        modelColor.addColumn("Tên Màu");
        modelColor.addColumn("Trạng Thái");

        tblMauSac.setModel(modelColor);
    }

    public void setTableTitleSize() {
        modelSize.addColumn("Mã Số");
        modelSize.addColumn("Kích Thước");
        modelSize.addColumn("Trạng Thái");

        tblKichThuoc.setModel(modelSize);
    }

    public void loadTableSize() {

        modelSize.setRowCount(0);

        listSize = sizeDao.selectAll();
        for (Size cl : listSize) {
            Object[] row = {
                cl.getId(),
                cl.getName(),
                cl.getActive() ? "Hoạt Động" : "Ngừng Hoạt động"

            };
            modelSize.addRow(row);
        }
        tblKichThuoc.setModel(modelSize);
    }
//    void edit() {
//        try {
//            int macl = (Integer) tblMauSac.getValueAt(index, 0);
//            Color model = colorDao.selectByID(macl + "");
//            if (model != null) {
//                setModel(model);
//
//            }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, "Lỗi truy vấn dữ liệu!");
//            e.printStackTrace();
//        }
//    }

    void setModelColor(Color model) {

        txtMauSac.setText(String.valueOf(model.getName()));
        if (model.getActive()) {
            cknHoatDong.setSelected(true);
        } else {
            cknNgungHoatDong.setSelected(true);
        }

    }

    void setModelSize(Size model) {

        txtSize.setText(String.valueOf(model.getName()));
        if (model.getActive()) {
            cknHoatDongKichThuoc.setSelected(true);
        } else {
            cknNgungHoatDongKickThuoc.setSelected(true);
        }

    }

    public Color getFormColor() {

//       Color color = new Color();
        color.setName(txtMauSac.getText());
        color.setActive(cknHoatDong.isSelected() ? true : false);

        return color;
    }

    public Size getFormSize() {

       // Size size = new Size();
        size.setName(txtSize.getText());
        size.setActive(cknHoatDongKichThuoc.isSelected() ? true : false);

        return size;
    }

    public void insertColor() {
        color = getFormColor();
        try {

            colorDao.insert(color);
            JOptionPane.showMessageDialog(this, "Thêm thành công!");
            loadTableColor();
            clearFormColor();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Thêm thất bại!");
        }

    }

    public void insertSize() {
        size = getFormSize();
        try {

            sizeDao.insert(size);
            JOptionPane.showMessageDialog(this, "Thêm thành công!");
            loadTableSize();
            clearFormSize();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Thêm thất bại!");
        }

    }

    public void updateColor() {
        color = getFormColor();
        try {
            int ind = (Integer) tblMauSac.getValueAt(index, 0);
            colorDao.update(color);
            loadTableColor();
            clearFormColor();
            JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Cập nhật thất bại!");
        }
    }

    public void updateSize() {
        size = getFormSize();
        try {
            sizeDao.update(size);
            loadTableSize();
            clearFormSize();
            JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Cập nhật thất bại!");
        }
    }

    public void deleteColor() {
//       color = getFormColor();
        try {
            if (JOptionPane.showConfirmDialog(this, "Xóa", "Xác nhận xóa!", JOptionPane.YES_NO_OPTION) == 0) {
                colorDao.delete(color.getId());
                System.out.println(color.getId());
                JOptionPane.showMessageDialog(this, "Xóa thành công!");
                loadTableColor();
                clearFormColor();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Xóa thất bại!");
        }
    }

    public void deleteSize() {
         size = getFormSize();
        try {
            if (JOptionPane.showConfirmDialog(this, "Xóa", "Xác nhận xóa!", JOptionPane.YES_NO_OPTION) == 0) {
                sizeDao.delete(size.getId());
               
                JOptionPane.showMessageDialog(this, "Xóa thành công!");
                loadTableSize();
                clearFormSize();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Xóa thất bại!");
        }
    }

    public void clearFormColor() {
        String t = "";
        txtMauSac.setText(t);

        bgrMauSac.clearSelection();

    }

    public void clearFormSize() {
        String t = "";
        txtSize.setText(t);

        bgrKichThuoc.clearSelection();

    }

    public void searchColor() {
        // DefaultTableModel model = (DefaultTableModel) tblMauSac.getModel();
        modelColor.setRowCount(0);
        //model.setRowCount(0);
        List<Color> list = colorDao.selectByObject(txtTimKiemMauSac.getText());
        if (list != null) {
            for (Color color : list) {
                Object[] row = {
                    color.getId(),
                    color.getName(),
                    color.getActive() ? "Hoạt Động" : "Ngừng Hoạt Động"
                };
                modelColor.addRow(row);
            }
            tblMauSac.setModel(modelColor);
        }
    }

    public void searchSize() {
        // DefaultTableModel model = (DefaultTableModel) tblMauSac.getModel();
        modelSize.setRowCount(0);
        //model.setRowCount(0);
        List<Size> list = sizeDao.selectByObject(txtTimKiemKichThuoc.getText());
        if (list != null) {
            for (Size size : list) {
                Object[] row = {
                    size.getId(),
                    size.getName(),
                    size.getActive() ? "Hoạt Động" : "Ngừng Hoạt Động"
                };
                modelSize.addRow(row);
            }
            tblKichThuoc.setModel(modelSize);
        }
    }

    private void txtMauSacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMauSacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMauSacActionPerformed

    private void txtSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSizeActionPerformed

    private void tblKichThuocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKichThuocMouseClicked
        // TODO add your handling code here:
         int index = tblKichThuoc.getSelectedRow();
        size = listSize.get(index);
        setModelSize(size);
    }//GEN-LAST:event_tblKichThuocMouseClicked
    XValidate vaildate = new XValidate();
    private void btnThemKichThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemKichThuocActionPerformed
        // TODO add your handling code here:
         if (vaildate.checkKichThuoc(txtSize)
                && vaildate.checkTrangThaiSize(cknHoatDongKichThuoc, cknNgungHoatDongKickThuoc)) {
            insertSize();
        }
    }//GEN-LAST:event_btnThemKichThuocActionPerformed

    private void btnXoaKichThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaKichThuocActionPerformed
        // TODO add your handling code here:
        deleteSize();
    }//GEN-LAST:event_btnXoaKichThuocActionPerformed

    private void btnThoatKichThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatKichThuocActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnThoatKichThuocActionPerformed

    private void btnMoiKichThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiKichThuocActionPerformed
        // TODO add your handling code here:
        clearFormSize();
    }//GEN-LAST:event_btnMoiKichThuocActionPerformed

    private void btnTimKiemKichThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemKichThuocActionPerformed
        // TODO add your handling code here:
        searchSize();
    }//GEN-LAST:event_btnTimKiemKichThuocActionPerformed

    private void txtTimKiemKichThuocKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKichThuocKeyReleased
        // TODO add your handling code here:
        if (txtTimKiemKichThuoc.getText().isEmpty()) {
            loadTableSize();
        }
    }//GEN-LAST:event_txtTimKiemKichThuocKeyReleased

    private void txtTimKiemMauSacKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemMauSacKeyReleased
        // TODO add your handling code here:
        if (txtTimKiemMauSac.getText().isEmpty()) {
            loadTableColor();
        }
    }//GEN-LAST:event_txtTimKiemMauSacKeyReleased

    private void tblMauSacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMauSacMouseClicked
        // TODO add your handling code here:
        int index = tblMauSac.getSelectedRow();
        color = listColor.get(index);
        setModelColor(color);
    }//GEN-LAST:event_tblMauSacMouseClicked

    private void btnSuaKichThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaKichThuocActionPerformed
        // TODO add your handling code here:
        if (vaildate.checkUpdateKichThuoc(txtSize)
                && vaildate.checkTrangThaiSize(cknHoatDongKichThuoc, cknNgungHoatDongKickThuoc)) {
            updateSize();
        }
    }//GEN-LAST:event_btnSuaKichThuocActionPerformed

    private void btnThemMauSacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMauSacActionPerformed
        // TODO add your handling code here:
        if (vaildate.checkTenMau(txtMauSac)
                && vaildate.checkTrangThaiColor(cknHoatDong, cknNgungHoatDong)) {
            insertColor();
        }
    }//GEN-LAST:event_btnThemMauSacActionPerformed

    private void btnSuaMauSacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaMauSacActionPerformed
        // TODO add your handling code here:
         if (vaildate.checkUpdateTenMau(txtMauSac)
                && vaildate.checkTrangThaiColor(cknHoatDong, cknNgungHoatDong)) {
            updateColor();
        }
    }//GEN-LAST:event_btnSuaMauSacActionPerformed

    private void btnXoaMauSacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaMauSacActionPerformed
        // TODO add your handling code here:
        deleteColor();
    }//GEN-LAST:event_btnXoaMauSacActionPerformed

    private void btnThoatMauSacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatMauSacActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnThoatMauSacActionPerformed

    private void btnMoiMauSacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiMauSacActionPerformed
        // TODO add your handling code here:
        clearFormColor();
    }//GEN-LAST:event_btnMoiMauSacActionPerformed

    private void btnTimKiemMauSacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemMauSacActionPerformed
        // TODO add your handling code here:
        searchColor();
    }//GEN-LAST:event_btnTimKiemMauSacActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormThuocTinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormThuocTinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormThuocTinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormThuocTinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormThuocTinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgrKichThuoc;
    private javax.swing.ButtonGroup bgrMauSac;
    private javax.swing.JButton btnMoiKichThuoc;
    private javax.swing.JButton btnMoiMauSac;
    private javax.swing.JButton btnSuaKichThuoc;
    private javax.swing.JButton btnSuaMauSac;
    private javax.swing.JButton btnThemKichThuoc;
    private javax.swing.JButton btnThemMauSac;
    private javax.swing.JButton btnThoatKichThuoc;
    private javax.swing.JButton btnThoatMauSac;
    private javax.swing.JButton btnTimKiemKichThuoc;
    private javax.swing.JButton btnTimKiemMauSac;
    private javax.swing.JButton btnXoaKichThuoc;
    private javax.swing.JButton btnXoaMauSac;
    private javax.swing.JCheckBox cknHoatDong;
    private javax.swing.JCheckBox cknHoatDongKichThuoc;
    private javax.swing.JCheckBox cknNgungHoatDong;
    private javax.swing.JCheckBox cknNgungHoatDongKickThuoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblKichThuoc;
    private javax.swing.JTable tblMauSac;
    private javax.swing.JTextField txtMauSac;
    private javax.swing.JTextField txtSize;
    private javax.swing.JTextField txtTimKiemKichThuoc;
    private javax.swing.JTextField txtTimKiemMauSac;
    // End of variables declaration//GEN-END:variables
}
